# Generated by Django 5.2.3 on 2025-06-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=100)),
                ('tipo_producto', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
